version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/triage-be2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Optional: add `target-branch: master` if you want PRs opened against master
